- src/nn/ops/gru.ts
The root cause is gru use tf.tidy that releases
some intermediate tensors incorrectly.
> Fix the gru issue for rnnoise example

- src/nn/ops/reduce.ts
- src/nn/ops/slice.ts
- src/nn/utils.ts
- test/ops/reduce.js
This pr is to fix #43, and also add more reduce tests which all would run PASS in both node.js and web browser.  
> Fixed reduce op issue of axes 0 and add more tests.

- src/nn/graph_builder.ts
- src/nn/ops/conv2d.ts
- test/ops/conv2d.js
> Supported conv2d op with 'ihwo' filterLayout option.

- test/cts/from_nnapi/test_generator/src/cts_generator.py
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_conv_float.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_conv_float_channels.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_conv_float_channels_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_conv_float_large.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_conv_float_large_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_conv_float_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_depthwise_conv2d_float_large.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_depthwise_conv2d_float_large_2.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_depthwise_conv2d_float_large_2_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_clamp_converted_from_depthwise_conv2d_float_large_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_conv_float_channels_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_conv_float_channels_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_conv_float_large_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_conv_float_large_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_conv_float_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_conv_float_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_depthwise_conv2d_float_large_2_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_depthwise_conv2d_float_large_2_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_depthwise_conv2d_float_large_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_add_clamp_converted_from_depthwise_conv2d_float_large_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_2/test_conv2d_add_clamp_converted_from_conv2d_dilation.js
- test/cts/from_nnapi/tests/V1_2/test_conv2d_add_clamp_converted_from_conv2d_v1_2.js
- test/cts/from_nnapi/tests/V1_2/test_conv2d_add_clamp_converted_from_depthwise_conv2d_v1_2.js
All updated CTS conv2d tests passed both in node.js and web browser.
> Optimized CTS convert tool with ihwo filterLayout. 

- test/ops/concat.js
This pr is to fix #61, new added concat test passed in both node.js and web browser.
> Added more concat tests with inputs.

- src/nn/ops/binary.ts
- test/ops/matmul.js
> Fixed matmul issue with an input of 1-D tensor.

- test/ops/pool2d.js
> Added pool2d tests of nhwc layout.

- test/ops/batch_norm.js
> Added tests for batchNormalization op.

- test/ops/conv2d.js
This pr is to :
1. add/update tests of autoPad option as 'same-upper' and 'same-lower'
2. add tests of conved fused bias and relu activation
3. update some tests purpose
> Added tests for conv2d op.

- src/nn/ops/gemm.ts
- test/ops/gemm.js
> Support updated spec for third input of gemm op.

- README.md
- node_setup.js
- package.json
- src/nn/context.ts
- src/nn/graph.ts
- test/utils.js
- webpack.config.js
Delivers wasm binaries to dist/ foloder for wasm backend.
> Support wasm backend

- test/models/tiny_yolov2_nchw.js
- test/models/tiny_yolov2_nhwc.js
Use ctsFp32RestrictAccuracyCriteria(1e-5, 5.0 * 1.1920928955078125e-7) for three model tests of TinyYolov2 nhwc model, these three tests would fail with this error message:
```
test tinyYolov2 nhwc
a(-9.346943855285645) b(-9.346960067749023) delta(0.00001621246337890625)
1) test_data_set_0
a(-7.7079949378967285) b(-7.708010673522949) delta(0.000015735626220703125)
2) test_data_set_1
a(2.4212486743927) b(2.421262264251709) delta(0.000013589859008789062)
3) test_data_set_2
0 passing (31s)
3 failing
1) test tinyYolov2 nhwc
test_data_set_0:
AssertionError: expected false to be true
+ expected - actual
-false
+true
at Module.checkValue (file:///path/webnn-polyfill/test/utils.js:37:12)
at testTinyYoloV2 (file:///path/webnn-polyfill/test/models/tiny_yolov2_nhwc.js:97:11)
at async …
```
> Add model tests of TinyYolov2 model.

- package.json
- webpack.config.js
> Fixed wasm JS script not working after minification

- test/index.html
- test/models.html
I‘m sorry that I missed to update index.html and models.html by adding TinyYoloV2 model tests in last #87.
> Enable run TinyYoloV2 model tests in Web browser.

- src/nn/graph_builder.ts
- test/cts/from_nnapi/test_generator/src/cts_generator.py
- test/cts/from_nnapi/test_generator/src/main.py
- test/cts/from_nnapi/test_generator/src/mapping_dict.py
- test/cts/from_nnapi/test_generator/src/test_generator.py
- test/cts/from_nnapi/tests/V1_0/test_conv2d_add_relu_converted_from_conv_float_channels_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_conv_float.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_conv_float_channels.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_conv_float_channels_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_conv_float_large.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_conv_float_large_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_conv_float_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_depthwise_conv2d_float_large.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_depthwise_conv2d_float_large_2.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_depthwise_conv2d_float_large_2_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_0/test_conv2d_converted_from_depthwise_conv2d_float_large_weights_as_inputs.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_conv_float_channels_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_conv_float_channels_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_conv_float_large_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_conv_float_large_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_conv_float_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_conv_float_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_depthwise_conv2d_float_large_2_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_depthwise_conv2d_float_large_2_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_depthwise_conv2d_float_large_relaxed.js
- test/cts/from_nnapi/tests/V1_1/test_conv2d_converted_from_depthwise_conv2d_float_large_weights_as_inputs_relaxed.js
- test/cts/from_nnapi/tests/V1_2/test_conv2d_converted_from_conv2d_dilation.js
- test/cts/from_nnapi/tests/V1_2/test_conv2d_converted_from_conv2d_v1_2.js
- test/cts/from_nnapi/tests/V1_2/test_conv2d_converted_from_depthwise_conv2d_v1_2.js
Add 76 conv2d CTS test with fused operations, fix #99. 
> Add conv2d CTS test with fused operations.

- test/index.html
- test/models.html
- test/models/resnet101v2_nhwc.js
- test/models/resnet50v2_nchw.js
Three model tests of ResNet50v2 nchw model all failed with test_data_set converted from sample test data of [ResNet50 V2](https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v2-7.tar.gz) ONNX model file.
[ResNet50v2_NCHW_Tests_result_details.xlsx](https://github.com/webmachinelearning/webnn-polyfill/files/6808095/ResNet50v2_NCHW_Tests_result_details.xlsx)
The error message of not satisfying accuracy tolerance, likes:
```
> cross-env NODE_ENV=test mocha --require ./node_setup.js --exit ./test/models/resnet50v2_nchw.js
test resnet50v2 nchw
a(-21.065582275390625) b(-22.073230743408203) delta(1.0076484680175781)
1) test_data_set_0
a(-20.56405258178711) b(-20.489290237426758) delta(0.07476234436035156)
2) test_data_set_1
a(-21.98280906677246) …
```
> Add model tests of ResNet model.

- test/cts/from_nnapi/README.md
- test/cts/from_nnapi/test_generator/src/mapping_dict.py
@BruceDai Please help check this PR. Thanks.
> Update mapping dict and "README" file

- src/nn/graph_builder.ts
- src/nn/ops/unary.ts
- test/index.html
- test/ops/hard_swish.js
> Supported hardSwish.

- test/ops.html
This pr is to fix missing update ops.html of last #113.
> Add hardSwish test into ops.html for testing in web browser.

- test/index.html
- test/models.html
- test/models/resnet50v2_nhwc.js
Depends on https://github.com/webmachinelearning/test-data/pull/14.
I will update test-data to latest once above pr was merged, here's local test status:
```
test resnet50v2 nhwc
✔ test_data_set_0 (7082ms)
✔ test_data_set_1 (7100ms)
✔ test_data_set_2 (7041ms)
✔ test_data_set_0 (fused ops) (5947ms)
✔ test_data_set_1 (fused ops) (5945ms)
✔ test_data_set_2 (fused ops) (5950ms)
6 passing (1m)
```
> Add model tests of ResNet50v2 NHWC model.

- test/models/mobilenetv2_nchw.js
- test/models/mobilenetv2_nhwc.js
- test/models/resnet101v2_nhwc.js
- test/models/resnet50v2_nchw.js
- test/models/resnet50v2_nhwc.js
- test/models/squeezenet1.0_nhwc.js
- test/models/squeezenet1.1_nchw.js
- test/models/tiny_yolov2_nchw.js
- test/models/tiny_yolov2_nhwc.js
Here's test result on my dev device with this pr.
```  
test mobilenetv2 nhwc
✔ test_data_set_0 (1581ms)
✔ test_data_set_1 (1510ms)
✔ test_data_set_2 (1501ms)
✔ test_data_set_0 (fused ops) (653ms)
✔ test_data_set_1 (fused ops) (656ms)
✔ test_data_set_2 (fused ops) (666ms)
6 passing (10s)
```
> Fix MobileNetv2 nhwc model tests with fused ops.

- package.json
- src/nn/graph_builder.ts
- src/nn/ops/pool2d.ts
- src/nn/utils.ts
- test/ops/pool2d.js
Fix #135.
Depend on https://github.com/tensorflow/tfjs/pull/5849.
> Support roundingType and outputSizes options for pool2d.

- test/ops/concat.js
> Add more concat op tests with multi inputs.

- test/ops/batch_norm.js
> Add batchNormalization op tests with 3D inputs.

- test/ops/pool2d.js
> Skip l2Pool2d tests.

- tsconfig.json
Another deploy failure https://github.com/webmachinelearning/webnn-polyfill/actions/runs/3520944049/jobs/5902363261 happened, this is a workaround to fix failure of running build-docs.
@Honry PTAL, thanks.
> Fixed failure when running build-docs.

- package.json
- webpack.config.js
> Make webnn-polyfill.js importable

- README.md
- package.json
- Add usage to README.md
- Add organization to the package name
> Prepare for npm publish

- .npmignore
- package.json
Address feedback on #196.
@Honry  PTAL, thanks.
> Drop test directory from NPM package.

- README.md
- node_setup.js
- package.json
- src/main.js
> Updated README file for clear usage.

- .github/workflows/build_test.yml
- package.json
- test/api/context.js
This pr is to fix #205 by upgrading TypeScript to latest version 4.9 according to a relevant discussion on https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64262. 
@Honry @huningxin PTAL, thanks.
> Fix ci failures

- src/nn/graph_builder.ts
- src/nn/ops/elu.ts
- test/index.html
- test/ops.html
- test/ops/elu.js
> Add implementation and tests for elu op

- src/nn/graph_builder.ts
- src/nn/ops/hard_sigmoid.ts
- test/index.html
- test/ops.html
- test/ops/hard_sigmoid.js
> Add implementation and tests for hardSigmoid

- src/nn/graph_builder.ts
- src/nn/ops/linear.ts
- test/index.html
- test/ops.html
- test/ops/linear.js
> Add implementation and tests for linear op

- src/nn/graph_builder.ts
- src/nn/ops/softplus.ts
- test/index.html
- test/ops.html
- test/ops/softplus.js
> Add implementation and tests for softplus op

- src/nn/graph_builder.ts
- src/nn/ops/unary.ts
- test/index.html
- test/ops.html
- test/ops/softsign.js
> Add implementation and test for softsign op

- package.json
> Upgrade version to 0.1.9
